### PR TITLE
add basic data privacy

### PR DESCRIPTION
**Pull request by hmoldenhauer**
basic pull request, not yet to merge

### CODE REVIEW

**Comment by The-Ludwig** [comment]
I think this is unneeded, isn't it? Impressum links to the right page.

**Comment by The-Ludwig** [comment]
> I think this is unneeded, isn't it? Impressum links to the right page.

@maxnoe ?

**Comment by maxnoe** [comment]
Impressum != Datenschutzerklärung, brauchen wir denke ich

**Comment by The-Ludwig** [comment]
Okay, dachte die section "Personenbezogene Daten" im Impressum reicht aus.

**Comment by maxnoe** [comment]
Ah, tatsache, ja, dass sollte erstmal reichen

**Pull request closed without merging**
